### ISSUE TITLE
Component does not start after update to 1.81.0b0

### ISSUE THREAD

**Issue by pjanning** [SukramJ/hahomematic#2052]
### I agree to the following

- [x] I have read the [documentation](https://github.com/sukramj/custom_homematic#custom_homematic) right now
- [x] I have read the [FAQs](https://github.com/sukramj/custom_homematic#frequently-asked-questions) right now
- [x] I am aware of the latest [release notes](https://github.com/sukramj/custom_homematic/releases)
- [x] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [x] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [x] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The component does not start after update. Always getting error: 

`Error occurred loading flow for integration homematicip_local: cannot import name 'ssdp' from 'homeassistant.helpers.service_info' (/usr/src/homeassistant/homeassistant/helpers/service_info/__init__.py)`

### What version of HomematicIP (local) has the issue?

1.81.0b0

### What was the last working version of HomematicIP (local)?

1.79.1

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20250118

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [x] TLS
- [x] callback data ([see](https://github.com/sukramj/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [x] Homematic IP
- [x] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [x] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt

```

**Comment by SukramJ** [comment]
How did you install it?

**Comment by pjanning** [comment]
I installed it using the Homeassistant Update function. I use HACS. 

Now i installed 1.80 and it works again. Error only happens in 1.81.0b0 at my setup. Do you need further information?

**Comment by SukramJ** [comment]
Are you running a HA version > 2025.2.0b0?

**Comment by pjanning** [comment]
No.  Is there no version check if they aren't compatible?

`Core 2025.1.4
Supervisor 2024.12.3
Operating System 14.2
Frontend 20250109.2`

**Comment by SukramJ** [comment]
Don't know how i works on you machine, but HACS should block 1.81.0b0  if HA verion is not >= 2025.2.0b0.

**Comment by pjanning** [comment]
Does it make sense to hand out a warning in the release notes? HACS does not block this in the current version.
