### ISSUE TITLE
not working since 1.88.0

### ISSUE THREAD

**Issue by eeeeeeeeven** [SukramJ/hahomematic#2335]
### Ich stimme dem Folgenden zu

- [x] Ich habe die [Dokumentation](https://github.com/sukramj/homematicip_local#homematicip_local) gelesen
- [x] Ich habe die [Fehlerbehebung-Dokumentation](https://github.com/SukramJ/aiohomematic/blob/devel/docs/homeassistant_troubleshooting.md) gelesen, und versucht das Problem selbstständig zu identifizieren/beheben.
- [x] Ich habe die [FAQs](https://github.com/sukramj/homematicip_local#frequently-asked-questions) gelesen
- [x] Ich kenne die neuesten [Versionshinweise](https://github.com/sukramj/homematicip_local/releases)
- [x] Mir ist klar, dass eine Integration, die über HACS installiert wurde, auch über HACS aktualisiert werden muss
- [x] Das Backend (CCU/Homegear/...) funktioniert wie erwartet, Geräte können angelernt werden und sind über deren eigene Benutzeroberfläche steuerbar
- [x] Ich verwende die neueste Version der Integration (und von Home Assistant).

### Das Problem

no connection to ccu3 after update to 1.88.0.

### Bei welcher Version von HomematicIP (lokal) tritt das Problem auf?

1.88.0

### Welche war die letzte funktionierende Version von Homematic(IP) Local for OpenCCU?

1.87.0

### Welche Art von Installation verwendest Du?

Home Assistant OS

### Welche Art von Installation verwendest Du als Homematic-Backend?

OpenCCU/RaspberryMatic Einzeln

### Welche Version des Homematic-Backends verwendest Du?

3.83.6.20250824

### Welche Hardware verwendest Du für das System?

CCU3 + RaspberryMatic

### Welche Konfigurationsdetails verwendest Du?

- [ ] TLS
- [ ] Callback Daten ([siehe](https://github.com/sukramj/homematicip_local#callback_host-and-callback_port))

### Welche Schnittstellen werden verwendet?

- [x] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)
- [ ] CuXD
- [ ] CCU-Jack

### Die vollständige Protokolldatei (sehr hilfreich). Gibt es in den Protokollen etwas, das nützlich sein könnte? Das Protokoll (Einstellungen/System/Protokolle -> Unveränderte Protokolle laden) ist die beste Quelle zur Fehlerbehebung!

```txt

```

**Comment by peterthepeter** [comment]
Same here, a attach the logs from HA.

> Logger: homeassistant.setup
Quelle: setup.py:343
Erstmals aufgetreten: 16:51:30 (1 Vorkommnis)
Zuletzt protokolliert: 16:51:30

Setup failed for custom integration 'homematicip_local': Unable to import component: cannot import name 'async_register_platform_entity_service' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1003, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 37, in <module>
    from .services import async_get_loaded_config_entries, async_setup_services, async_unload_services
  File "/config/custom_components/homematicip_local/services.py", line 29, in <module>
    from homeassistant.helpers.service import (
    ...<3 lines>...
    )
ImportError: cannot import name 'async_register_platform_entity_service' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 37, in <module>
    from .services import async_get_loaded_config_entries, async_setup_services, async_unload_services
  File "/config/custom_components/homematicip_local/services.py", line 29, in <module>
    from homeassistant.helpers.service import (
    ...<3 lines>...
    )
ImportError: cannot import name 'async_register_platform_entity_service' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)

**Comment by DatDucati** [comment]
Have the same error. Home Assistant 2025.9.4

**Comment by SukramJ** [comment]
#2328
