### ISSUE TITLE
Startup problem after upgrade

### ISSUE THREAD

**Issue by LineF** [SukramJ/hahomematic#979]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,

after upgrading homematicip to the latest version it doesn't come up after restarting HA.
These error messages are reported:

![2023-03-01 11_48_19-Einstellungen – Home Assistant](https://user-images.githubusercontent.com/11915423/222119542-23ccb0e1-ade3-43ce-a846-fb3a0a886a7c.png)

I had to do a full restore to get homematicip up and running again.
All versions (HAOS, Supervisor etc.) are at the latest version.

Martin

### What version of HomematicIP (local) has the issue?

1.33

### What was the last working version of HomematicIP (local)?

1.32

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Looks like a communication problem on your system.
This is not related to the integration.

**Comment by LineF** [comment]
But the error message tells me "...requirements not found...hahomematic==2023.2.11"
That doesn't sound like a communication problem.
And 1.32 works without any problems. Why should 1.33 then get a communictation problem?

What can I do? How can I help?

...and now I see in your latest commit that there is a change regarding just this requirement...

Martin

**Comment by SveLil** [comment]
Same here after the upgrade. I managed to get a
`
Unable to install package hahomematic==2023.2.11: ERROR: Cannot install hahomematic==2023.2.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
`
Additionally, I can't even delete the component:
`
ImportError: cannot import name 'cleanup_cache_dirs' from 'hahomematic.support' (/usr/local/lib/python3.10/site-packages/hahomematic/support.py)
`

**Comment by SukramJ** [comment]
Do you use the latest HA?

**Comment by SveLil** [comment]
I'm using 2023.2.2 will try with the update

**Comment by LineF** [comment]
Mine is 2023.2.4, Supervisor 2023.01.1, OS 9.5

**Comment by SukramJ** [comment]
>  I am running the latest version of the custom_component (and Home Assistant)

**Comment by SveLil** [comment]
Works after updating to 2023.2.5

**Comment by LineF** [comment]
yes, can confirm too. Works with 2023.2.5.
Didn't have installed latest version of HA accidentally... was omitted...
Thanks!
