### ISSUE TITLE
No device updates (events) since v1.64

### ISSUE THREAD

**Issue by j-hallier** [SukramJ/hahomematic#1738]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After updating to v1.64 it's only possible to control my thermostats (HM-CC-RT-DN and HmIP-eTRV-B-2 R4M) but not to receive any status information (temperature, valve state, ...). This error might be related to an analysis of the device configuration during startup. For each thermostat I can see (in the debug log) an error <FIRE_entitiy_updated_EVENT failed: 'CeRfThermostat' object has no attribute 'refreshed_at'>

### What version of HomematicIP (local) has the issue?

1.64.0

### What was the last working version of HomematicIP (local)?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[error.log](https://github.com/user-attachments/files/17220659/error.log)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-10-01 21:37:52.748 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new climate.homematicip_local entity: climate.wozi1_thermostat
2024-10-01 21:37:52.748 WARNING (MainThread) [hahomematic.platforms.entity] FIRE_entity_updated_EVENT failed: 'CeRfThermostat' object has no attribute 'refreshed_at'
2024-10-01 21:37:52.748 WARNING (MainThread) [hahomematic.platforms.entity] FIRE_entity_updated_EVENT failed: 'CeRfThermostat' object has no attribute 'refreshed_at'
2024-10-01 21:37:52.748 WARNING (MainThread) [hahomematic.platforms.entity] 

and later also 
2024-10-01 21:37:52.820 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.homematicip_local entity: binary_sensor.hm_sec_sd_2_neq0507947
2024-10-01 21:37:52.825 WARNING (MainThread) [hahomematic.platforms.entity] FIRE_entity_updated_EVENT failed: 'HmBinarySensor' object has no attribute 'refreshed_at'
```

### Additional information

Update trials to version v1.65 and v1.66 failed because loading of the configuration page failed

**Comment by SukramJ** [comment]
Sorry, i don't support old versions.

**Comment by j-hallier** [comment]
Sorry for insisting: why are you sure, that you have not made any mistake some times ago ?

**Comment by SukramJ** [comment]
> why are you sure, that you have not made any mistake some times ago ?

Sure i did, but why should i waste my time in investigating a problem in an old version?
Update to the latest, and comeback if the issue still exists.

**Comment by j-hallier** [comment]
I would do, if I could. I'll have to write my next ticket, because I cannot even configure 1.66.
