### ISSUE TITLE
HmIPW-DRBL4 - AttributeError: 'CeIpBlind' object has no attribute 'operation_mode' 

### ISSUE THREAD

**Issue by fl0x53** [SukramJ/hahomematic#1792]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After Updating Homematic(IP) Local to v1.68.0 Home Assistant can't create cover entites due to "AttributeError: 'CeIpBlind' object has no attribute 'operation_mode'" in cover.py (see log)

### What version of HomematicIP (local) has the issue?

1.68.0

### What was the last working version of HomematicIP (local)?

1.67.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[home-assistant_homematicip_local_2024-10-25T16-00-51.000Z.log](https://github.com/user-attachments/files/17524746/home-assistant_homematicip_local_2024-10-25T16-00-51.000Z.log)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.helpers.dispatcher
Quelle: util/logging.py:95
Erstmals aufgetreten: 17:44:57 (1 Vorkommnisse)
Zuletzt protokolliert: 17:44:57

Exception in async_add_cover when dispatching 'homematicip_local-new-entity-906cada5b823c1c437ae83639ed88f91-cover': ({<hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139820>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccd820>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b9040>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340e870>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b90d0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff641398e0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340e930>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccd940>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139970>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340e9c0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139a00>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccda00>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64a99a00>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b9220>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340ea80>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139a90>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccda90>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b92b0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139b20>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccdb20>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6d88ab40>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340eb40>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b9340>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139bb0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccdbb0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340ebd0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b93d0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccdc40>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff70b96450>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340ec60>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b9460>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccdcd0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6d9dbce0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340ecf0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b94f0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccd550>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139580>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340ed80>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139610>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340ee10>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b8e90>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff641396d0>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64a98f20>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340e750>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff64139760>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff63ccd760>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff634b8f80>, <hahomematic.platforms.custom.cover.CeIpBlind object at 0xffff6340e7b0>},) Traceback (most recent call last): File "/config/custom_components/homematicip_local/cover.py", line 54, in async_add_cover if hm_entity.operation_mode and hm_entity.operation_mode == "SHUTTER": ^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'CeIpBlind' object has no attribute 'operation_mode'
```

**Comment by fl0x53** [comment]
Solved it 🤦
The root cause is that HACS messed up python dependencies once again. It was still using hahomematic-2024.10.8 and not 2024.10.13.

**Comment by fl0x53** [comment]
Solved it 🤦
The root cause is that HACS messed up python dependencies once again. It was still using hahomematic-2024.10.8 and not 2024.10.13.
