### ISSUE TITLE
Does not start with 2023.5.3

### ISSUE THREAD

**Issue by GLehnhoff** [SukramJ/hahomematic#1063]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Neither 1.36 nor 1.37 is running. 

### What version of HomematicIP (local) has the issue?

1.36

### What was the last working version of HomematicIP (local)?

1.35 with 2023.4.x. It stopped working after upgrade to 2023.5.3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.69.7

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us?

```txt
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/hahm/__init__.py:26
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 20:34:02 (3 occurrences)
Last logged: 20:34:59

Error setting up entry RaspberryMatic for hahm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hahm/__init__.py", line 26, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, HAHM_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by SukramJ** [comment]
Using the search or checking the [pinned](https://github.com/danielperna84/hahomematic/issues/1049) saves time for everybody
